#!/usr/bin/env python

# This script plots data from a csv file of LFM output generated by Paraview.

import pandas as pd
import matplotlib.pyplot as plt
import sys

plt.style.use('dredger_default')

# reading solar wind data into a dataframe

sw_file = sys.argv[1]
df = pd.read_csv(sw_file,usecols=[0,1,2,3,4,25],header=0,
                 names=['Bx, By Magnitude (nT)','Bx (nT)','By (nT)','Bz (nT)','Plasma Density','X (Re)'],engine='python')

# plotting the desired variables

axs = df.plot(kind='line',x='X (Re)',y=['Bx, By Magnitude (nT)','Bx (nT)','By (nT)','Bz (nT)','Plasma Density'],
        subplots=True,grid=False,layout=(5,1),sharex=True,sharey=False,legend=False,
        title='LFM Output Across Magnetopause (Nose)',figsize=(10,12),color='k',linewidth=0.75)
for ax in axs.flat:
    h,l = ax.get_legend_handles_labels()
    ax.set(ylabel=l[0])

plt.subplots_adjust(top=0.9,bottom=0.1,hspace=0)

plt.savefig("test_savedata_paraview_mpl.png") # CHANGE MANUALLY
